"""Integration tests for POST /printers/{id}/uploads/import."""

from __future__ import annotations

import io


SAMPLE_CSV = (
    "job_id,recorded_at,printed_pages,color_pages,bw_pages\n"
    "JOB-1,2026-05-23 10:00:00,10,4,6\n"
    "JOB-2,2026-05-23 10:05:00,2,0,2\n"
).encode("utf-8")


def _post(client, printer_id, body=SAMPLE_CSV, key="test-ingest-key", filename="t.csv"):
    files = {"file": (filename, io.BytesIO(body), "text/csv")}
    headers = {"X-API-Key": key} if key else {}
    return client.post(f"/api/v1/printers/{printer_id}/uploads/import", files=files, headers=headers)


def test_happy_path_returns_200_with_contract(client, printer_with_mapping):
    r = _post(client, printer_with_mapping.id)
    assert r.status_code == 200, r.text
    j = r.json()
    assert j["status"] == "success"
    assert j["printer_id"] == printer_with_mapping.id
    assert j["rows_total"] == 2
    assert j["rows_imported"] == 2
    assert j["rows_skipped"] == 0
    assert isinstance(j["batch_id"], int)
    assert j["source_filename"] == "t.csv"


def test_duplicate_repost_skips_all(client, printer_with_mapping):
    r1 = _post(client, printer_with_mapping.id)
    r2 = _post(client, printer_with_mapping.id)
    assert r1.status_code == 200
    assert r2.status_code == 200
    j2 = r2.json()
    assert j2["rows_imported"] == 0
    assert j2["rows_skipped"] == 2


def test_missing_api_key_returns_401(client, printer_with_mapping):
    r = _post(client, printer_with_mapping.id, key=None)
    assert r.status_code == 401
    assert r.json()["detail"]["error_code"] == "UNAUTHORIZED"


def test_wrong_api_key_returns_401(client, printer_with_mapping):
    r = _post(client, printer_with_mapping.id, key="nope")
    assert r.status_code == 401


def test_unknown_printer_returns_404(client):
    r = _post(client, 999999)
    assert r.status_code == 404
    j = r.json()
    assert j["error_code"] == "PRINTER_NOT_FOUND"


def test_malformed_csv_returns_400(client, printer_with_mapping):
    r = _post(client, printer_with_mapping.id, body=b"\x00\x01garbage")
    assert r.status_code == 400
    j = r.json()
    assert j["error_code"] == "INVALID_CSV"


def test_source_filename_override(client, printer_with_mapping):
    files = {"file": ("autogenerated.csv", io.BytesIO(SAMPLE_CSV), "text/csv")}
    data = {"source_filename": "drive-original.csv"}
    r = client.post(
        f"/api/v1/printers/{printer_with_mapping.id}/uploads/import",
        files=files,
        data=data,
        headers={"X-API-Key": "test-ingest-key"},
    )
    assert r.status_code == 200
    assert r.json()["source_filename"] == "drive-original.csv"
